package com.github.alexthe666.iceandfire.client.model;

import com.github.alexthe666.iceandfire.entity.EntityAutomatonFlying;
import net.ilexiconn.llibrary.client.model.ModelAnimator;
import net.ilexiconn.llibrary.server.animation.IAnimatedEntity;
import net.minecraft.client.model.ModelRenderer;
import net.minecraft.entity.Entity;

/**
 * Automaton_flying_tabulatest - Either Mojang or a mod author
 * Created using Tabula 7.1.0
 */
public class ModelAutomatonFlying extends ModelDragonBase {
    public ModelRenderer AutomatonMain;
    public ModelRenderer Detector;
    public ModelRenderer Connector;
    public ModelRenderer Ammo;
    public ModelRenderer D_BODYChildChild0;
    public ModelRenderer D_BODYChildChild1;
    public ModelRenderer Wing;
    public ModelRenderer Shooter;
    public ModelRenderer D_BODYChildChild0_1;
    public ModelRenderer D_BODYChildChild1_1;
    public ModelRenderer D_BODYChildChild2;
    public ModelRenderer D_BODYChildChild3;
    public ModelRenderer D_BODYChildChild4;
    public ModelRenderer D_BODYChildChild5;
    public ModelRenderer D_BODYChildChild6;
    public ModelRenderer D_BODYChildChild7;
    public ModelRenderer D_BODYChildChild8;
    public ModelRenderer D_BODYChildChild9;
    public ModelRenderer D_BODYChildChild10;
    public ModelRenderer D_BODYChildChild11;
    public ModelRenderer D_BODYChildChild12;
    public ModelRenderer D_BODYChildChild13;
    public ModelRenderer D_BODYChildChild14;
    public ModelRenderer D_BODYChildChild0_2;
    public ModelRenderer D_BODYChildChild1_2;
    public ModelRenderer D_BODYChildChild2_1;
    public ModelRenderer D_BODYChildChild3_1;
    public ModelRenderer D_BODYChildChild4_1;
    public ModelRenderer D_BODYChildChild5_1;
    public ModelRenderer D_BODYChildChild6_1;
    public ModelRenderer D_BODYChildChild7_1;
    public ModelRenderer D_BODYChildChild8_1;
    public ModelRenderer D_BODYChildChild9_1;
    public ModelRenderer D_BODYChildChild10_1;
    public ModelRenderer D_BODYChildChild11_1;
    public ModelRenderer D_BODYChildChild12_1;
    public ModelRenderer D_BODYChildChild13_1;
    public ModelRenderer D_BODYChildChild14_1;
    public ModelRenderer D_BODYChildChild1_3;
    public ModelRenderer D_BODYChildChild2_2;
    public ModelRenderer D_BODYChildChild3_2;
    public ModelRenderer Pot2;
    public ModelRenderer Flame2;
    public ModelRenderer D_BODYChildChildChild2;
    public ModelRenderer D_BODYChildChildChild3;
    public ModelRenderer D_BODYChildChildChild4;
    public ModelRenderer D_BODYChildChildChild5;
    public ModelRenderer D_BODYChildChildChild0;
    public ModelRenderer Pot1;
    public ModelRenderer Flame1;
    public ModelRenderer D_BODYChildChildChild0_1;
    public ModelRenderer D_BODYChildChildChild2_1;
    public ModelRenderer D_BODYChildChildChild3_1;
    public ModelRenderer D_BODYChildChildChild4_1;
    public ModelRenderer D_BODYChildChildChild5_1;
    private final ModelAnimator animator;

    public ModelAutomatonFlying() {
        this.textureWidth = 150;
        this.textureHeight = 80;
        this.D_BODYChildChild6 = new ModelRenderer(this, 41, 52);
        this.D_BODYChildChild6.setRotationPoint(9.0F, -0.5F, 0.0F);
        this.D_BODYChildChild6.addBox(-4.0F, -25.0F, -9.0F, 12, 1, 1, 0.0F);
        this.D_BODYChildChild11 = new ModelRenderer(this, 37, 58);
        this.D_BODYChildChild11.setRotationPoint(9.0F, -0.5F, 0.0F);
        this.D_BODYChildChild11.addBox(0.0F, -13.0F, 1.0F, 1, 5, 1, 0.0F);
        this.D_BODYChildChild0_2 = new ModelRenderer(this, 118, 35);
        this.D_BODYChildChild0_2.setRotationPoint(-7.0F, -0.5F, 0.0F);
        this.D_BODYChildChild0_2.addBox(-9.0F, -27.5F, 2.0F, 1, 5, 5, 0.0F);
        this.Pot1 = new ModelRenderer(this, 0, 48);
        this.Pot1.mirror = true;
        this.Pot1.setRotationPoint(-8.25F, -25.0F, 4.5F);
        this.Pot1.addBox(0.25F, -4.5F, -4.5F, 9, 9, 9, 0.0F);
        this.D_BODYChildChildChild5_1 = new ModelRenderer(this, 79, 56);
        this.D_BODYChildChildChild5_1.mirror = true;
        this.D_BODYChildChildChild5_1.setRotationPoint(0.0F, 0.0F, 0.0F);
        this.D_BODYChildChildChild5_1.addBox(3.25F, -5.5F, 6.5F, 2, 4, 2, 0.0F);
        this.D_BODYChildChild2 = new ModelRenderer(this, 41, 52);
        this.D_BODYChildChild2.setRotationPoint(9.0F, -0.5F, 0.0F);
        this.D_BODYChildChild2.addBox(-4.0F, -25.0F, 15.0F, 12, 1, 1, 0.0F);
        this.D_BODYChildChild5_1 = new ModelRenderer(this, 119, 49);
        this.D_BODYChildChild5_1.mirror = true;
        this.D_BODYChildChild5_1.setRotationPoint(-7.0F, -0.5F, 0.0F);
        this.D_BODYChildChild5_1.addBox(4.0F, -25.0F, -9.0F, 1, 1, 9, 0.0F);
        this.D_BODYChildChild7_1 = new ModelRenderer(this, 0, 70);
        this.D_BODYChildChild7_1.mirror = true;
        this.D_BODYChildChild7_1.setRotationPoint(-7.0F, -0.5F, 0.0F);
        this.D_BODYChildChild7_1.addBox(-8.0F, -8.0F, 0.0F, 9, 1, 9, 0.0F);
        this.Flame2 = new ModelRenderer(this, 53, 62);
        this.Flame2.mirror = true;
        this.Flame2.setRotationPoint(0.0F, 0.0F, 0.0F);
        this.Flame2.addBox(1.0F, -13.0F, 2.0F, 5, 5, 5, 0.0F);
        this.D_BODYChildChild3_1 = new ModelRenderer(this, 123, 53);
        this.D_BODYChildChild3_1.mirror = true;
        this.D_BODYChildChild3_1.setRotationPoint(-7.0F, -0.5F, 0.0F);
        this.D_BODYChildChild3_1.addBox(3.0F, -25.0F, 10.0F, 1, 1, 5, 0.0F);
        this.D_BODYChildChild1 = new ModelRenderer(this, 117, 21);
        this.D_BODYChildChild1.setRotationPoint(3.6F, -17.99F, 1.01F);
        this.D_BODYChildChild1.addBox(-5.0F, 0.9F, -0.5F, 1, 5, 5, 0.0F);
        this.setRotateAngle(D_BODYChildChild1, -0.7853981633974483F, 0.0F, 0.0F);
        this.D_BODYChildChild12 = new ModelRenderer(this, 49, 55);
        this.D_BODYChildChild12.mirror = true;
        this.D_BODYChildChild12.setRotationPoint(9.0F, -0.5F, 0.0F);
        this.D_BODYChildChild12.addBox(-4.0F, -16.0F, 3.0F, 4, 1, 3, 0.0F);
        this.AutomatonMain = new ModelRenderer(this, 0, 0);
        this.AutomatonMain.setRotationPoint(0.0F, 30.0F, 0.0F);
        this.AutomatonMain.addBox(0.0F, 0.0F, 0.0F, 0, 0, 0, 0.0F);
        this.setRotateAngle(AutomatonMain, 0.0F, 3.141592653589793F, 0.0F);
        this.Detector = new ModelRenderer(this, 0, 0);
        this.Detector.setRotationPoint(0.0F, 0.0F, 0.0F);
        this.Detector.addBox(-3.0F, -23.0F, -3.0F, 8, 9, 12, 0.0F);
        this.setRotateAngle(Detector, 0.0F, 3.141592653589793F, 0.0F);
        this.D_BODYChildChild4 = new ModelRenderer(this, 119, 49);
        this.D_BODYChildChild4.setRotationPoint(9.0F, -0.5F, 0.0F);
        this.D_BODYChildChild4.addBox(8.0F, -25.0F, -9.0F, 1, 1, 9, 0.0F);
        this.D_BODYChildChildChild4_1 = new ModelRenderer(this, 77, 49);
        this.D_BODYChildChildChild4_1.setRotationPoint(0.0F, 0.0F, 0.0F);
        this.D_BODYChildChildChild4_1.addBox(3.25F, -1.5F, 4.5F, 2, 2, 4, 0.0F);
        this.D_BODYChildChild8_1 = new ModelRenderer(this, 37, 58);
        this.D_BODYChildChild8_1.mirror = true;
        this.D_BODYChildChild8_1.setRotationPoint(-7.0F, -0.5F, 0.0F);
        this.D_BODYChildChild8_1.addBox(-7.0F, -13.0F, 1.0F, 1, 5, 1, 0.0F);
        this.D_BODYChildChild5 = new ModelRenderer(this, 119, 49);
        this.D_BODYChildChild5.setRotationPoint(9.0F, -0.5F, 0.0F);
        this.D_BODYChildChild5.addBox(-5.0F, -25.0F, -9.0F, 1, 1, 9, 0.0F);
        this.D_BODYChildChild12_1 = new ModelRenderer(this, 49, 55);
        this.D_BODYChildChild12_1.setRotationPoint(-7.0F, -0.5F, 0.0F);
        this.D_BODYChildChild12_1.addBox(0.0F, -16.0F, 3.0F, 4, 1, 3, 0.0F);
        this.D_BODYChildChild2_2 = new ModelRenderer(this, 62, 23);
        this.D_BODYChildChild2_2.setRotationPoint(0.0F, 0.0F, 0.0F);
        this.D_BODYChildChild2_2.addBox(-1.0F, -2.0F, -21.0F, 2, 1, 42, 0.0F);
        this.D_BODYChildChild6_1 = new ModelRenderer(this, 41, 52);
        this.D_BODYChildChild6_1.mirror = true;
        this.D_BODYChildChild6_1.setRotationPoint(-7.0F, -0.5F, 0.0F);
        this.D_BODYChildChild6_1.addBox(-8.0F, -25.0F, -9.0F, 12, 1, 1, 0.0F);
        this.D_BODYChildChild10_1 = new ModelRenderer(this, 37, 58);
        this.D_BODYChildChild10_1.mirror = true;
        this.D_BODYChildChild10_1.setRotationPoint(-7.0F, -0.5F, 0.0F);
        this.D_BODYChildChild10_1.addBox(-1.0F, -13.0F, 7.0F, 1, 5, 1, 0.0F);
        this.Connector = new ModelRenderer(this, 53, 9);
        this.Connector.setRotationPoint(0.0F, 0.0F, 0.0F);
        this.Connector.addBox(-6.0F, -28.0F, -10.0F, 10, 5, 11, 0.0F);
        this.Ammo = new ModelRenderer(this, 40, 0);
        this.Ammo.mirror = true;
        this.Ammo.setRotationPoint(0.0F, 0.0F, 0.0F);
        this.Ammo.addBox(-1.2F, -23.0F, -14.0F, 6, 10, 4, 0.0F);
        this.D_BODYChildChild0 = new ModelRenderer(this, 117, 21);
        this.D_BODYChildChild0.mirror = true;
        this.D_BODYChildChild0.setRotationPoint(3.6F, -17.99F, 1.01F);
        this.D_BODYChildChild0.addBox(-1.2F, 0.9F, -0.5F, 1, 5, 5, 0.0F);
        this.setRotateAngle(D_BODYChildChild0, -0.7853981633974483F, 0.0F, 0.0F);
        this.Shooter = new ModelRenderer(this, 1, 21);
        this.Shooter.setRotationPoint(1.0F, -13.76F, -0.24F);
        this.Shooter.addBox(-4.0F, 0.75F, -3.75F, 8, 6, 18, 0.0F);
        this.D_BODYChildChildChild3_1 = new ModelRenderer(this, 77, 49);
        this.D_BODYChildChildChild3_1.mirror = true;
        this.D_BODYChildChildChild3_1.setRotationPoint(0.0F, 0.0F, 0.0F);
        this.D_BODYChildChildChild3_1.addBox(3.25F, -1.5F, -8.5F, 2, 2, 4, 0.0F);
        this.D_BODYChildChild1_3 = new ModelRenderer(this, 39, 22);
        this.D_BODYChildChild1_3.setRotationPoint(0.0F, 0.0F, 0.0F);
        this.D_BODYChildChild1_3.addBox(-1.0F, 1.0F, -1.0F, 2, 5, 2, 0.0F);
        this.D_BODYChildChild9_1 = new ModelRenderer(this, 37, 58);
        this.D_BODYChildChild9_1.mirror = true;
        this.D_BODYChildChild9_1.setRotationPoint(-7.0F, -0.5F, 0.0F);
        this.D_BODYChildChild9_1.addBox(-7.0F, -13.0F, 7.0F, 1, 5, 1, 0.0F);
        this.D_BODYChildChildChild5 = new ModelRenderer(this, 79, 56);
        this.D_BODYChildChildChild5.setRotationPoint(0.0F, 0.0F, 0.0F);
        this.D_BODYChildChildChild5.addBox(-5.25F, -5.5F, 6.5F, 2, 4, 2, 0.0F);
        this.D_BODYChildChild3_2 = new ModelRenderer(this, 0, 45);
        this.D_BODYChildChild3_2.setRotationPoint(0.0F, 0.0F, 0.0F);
        this.D_BODYChildChild3_2.addBox(-21.0F, -2.0F, -1.0F, 42, 1, 2, 0.0F);
        this.D_BODYChildChild14_1 = new ModelRenderer(this, 67, 69);
        this.D_BODYChildChild14_1.mirror = true;
        this.D_BODYChildChild14_1.setRotationPoint(-7.0F, -0.5F, 0.0F);
        this.D_BODYChildChild14_1.addBox(-7.0F, -16.0F, 1.0F, 7, 3, 7, 0.0F);
        this.D_BODYChildChild8 = new ModelRenderer(this, 37, 58);
        this.D_BODYChildChild8.setRotationPoint(9.0F, -0.5F, 0.0F);
        this.D_BODYChildChild8.addBox(6.0F, -13.0F, 1.0F, 1, 5, 1, 0.0F);
        this.D_BODYChildChild14 = new ModelRenderer(this, 67, 69);
        this.D_BODYChildChild14.setRotationPoint(9.0F, -0.5F, 0.0F);
        this.D_BODYChildChild14.addBox(0.0F, -16.0F, 1.0F, 7, 3, 7, 0.0F);
        this.D_BODYChildChildChild2_1 = new ModelRenderer(this, 68, 49);
        this.D_BODYChildChildChild2_1.mirror = true;
        this.D_BODYChildChildChild2_1.setRotationPoint(0.0F, 0.0F, 0.0F);
        this.D_BODYChildChildChild2_1.addBox(3.25F, 0.5F, -8.5F, 2, 4, 2, 0.0F);
        this.D_BODYChildChild10 = new ModelRenderer(this, 37, 58);
        this.D_BODYChildChild10.setRotationPoint(9.0F, -0.5F, 0.0F);
        this.D_BODYChildChild10.addBox(0.0F, -13.0F, 7.0F, 1, 5, 1, 0.0F);
        this.D_BODYChildChild13_1 = new ModelRenderer(this, 30, 67);
        this.D_BODYChildChild13_1.mirror = true;
        this.D_BODYChildChild13_1.setRotationPoint(-7.0F, -0.5F, 0.0F);
        this.D_BODYChildChild13_1.addBox(-7.0F, -7.0F, 1.0F, 7, 2, 7, 0.0F);
        this.Flame1 = new ModelRenderer(this, 53, 62);
        this.Flame1.setRotationPoint(0.0F, 0.0F, 0.0F);
        this.Flame1.addBox(-6.0F, -13.0F, 2.0F, 5, 5, 5, 0.0F);
        this.D_BODYChildChild7 = new ModelRenderer(this, 0, 70);
        this.D_BODYChildChild7.setRotationPoint(9.0F, -0.5F, 0.0F);
        this.D_BODYChildChild7.addBox(-1.0F, -8.0F, 0.0F, 9, 1, 9, 0.0F);
        this.Wing = new ModelRenderer(this, 35, 31);
        this.Wing.setRotationPoint(1.0F, -34.0F, 4.0F);
        this.Wing.addBox(-2.0F, -3.0F, -2.0F, 4, 4, 4, 0.0F);
        this.D_BODYChildChildChild0 = new ModelRenderer(this, 53, 28);
        this.D_BODYChildChildChild0.setRotationPoint(0.0F, 0.0F, 0.0F);
        this.D_BODYChildChildChild0.addBox(-11.25F, -1.5F, -1.5F, 2, 3, 3, 0.0F);
        this.D_BODYChildChild3 = new ModelRenderer(this, 123, 53);
        this.D_BODYChildChild3.setRotationPoint(9.0F, -0.5F, 0.0F);
        this.D_BODYChildChild3.addBox(-4.0F, -25.0F, 10.0F, 1, 1, 5, 0.0F);
        this.D_BODYChildChild1_1 = new ModelRenderer(this, 119, 49);
        this.D_BODYChildChild1_1.setRotationPoint(9.0F, -0.5F, 0.0F);
        this.D_BODYChildChild1_1.addBox(8.0F, -25.0F, 7.0F, 1, 1, 9, 0.0F);
        this.Pot2 = new ModelRenderer(this, 0, 48);
        this.Pot2.setRotationPoint(8.25F, -25.0F, 4.5F);
        this.Pot2.addBox(-9.25F, -4.5F, -4.5F, 9, 9, 9, 0.0F);
        this.D_BODYChildChild11_1 = new ModelRenderer(this, 37, 58);
        this.D_BODYChildChild11_1.mirror = true;
        this.D_BODYChildChild11_1.setRotationPoint(-7.0F, -0.5F, 0.0F);
        this.D_BODYChildChild11_1.addBox(-1.0F, -13.0F, 1.0F, 1, 5, 1, 0.0F);
        this.D_BODYChildChildChild2 = new ModelRenderer(this, 68, 49);
        this.D_BODYChildChildChild2.setRotationPoint(0.0F, 0.0F, 0.0F);
        this.D_BODYChildChildChild2.addBox(-5.25F, 0.5F, -8.5F, 2, 4, 2, 0.0F);
        this.D_BODYChildChild4_1 = new ModelRenderer(this, 119, 49);
        this.D_BODYChildChild4_1.mirror = true;
        this.D_BODYChildChild4_1.setRotationPoint(-7.0F, -0.5F, 0.0F);
        this.D_BODYChildChild4_1.addBox(-9.0F, -25.0F, -9.0F, 1, 1, 9, 0.0F);
        this.D_BODYChildChild0_1 = new ModelRenderer(this, 118, 35);
        this.D_BODYChildChild0_1.mirror = true;
        this.D_BODYChildChild0_1.setRotationPoint(9.0F, -0.5F, 0.0F);
        this.D_BODYChildChild0_1.addBox(8.0F, -27.5F, 2.0F, 1, 5, 5, 0.0F);
        this.D_BODYChildChildChild0_1 = new ModelRenderer(this, 53, 28);
        this.D_BODYChildChildChild0_1.mirror = true;
        this.D_BODYChildChildChild0_1.setRotationPoint(0.0F, 0.0F, 0.0F);
        this.D_BODYChildChildChild0_1.addBox(9.25F, -1.5F, -1.5F, 2, 3, 3, 0.0F);
        this.D_BODYChildChild2_1 = new ModelRenderer(this, 41, 52);
        this.D_BODYChildChild2_1.mirror = true;
        this.D_BODYChildChild2_1.setRotationPoint(-7.0F, -0.5F, 0.0F);
        this.D_BODYChildChild2_1.addBox(-8.0F, -25.0F, 15.0F, 12, 1, 1, 0.0F);
        this.D_BODYChildChild13 = new ModelRenderer(this, 30, 67);
        this.D_BODYChildChild13.setRotationPoint(9.0F, -0.5F, 0.0F);
        this.D_BODYChildChild13.addBox(0.0F, -7.0F, 1.0F, 7, 2, 7, 0.0F);
        this.D_BODYChildChild1_2 = new ModelRenderer(this, 119, 49);
        this.D_BODYChildChild1_2.mirror = true;
        this.D_BODYChildChild1_2.setRotationPoint(-7.0F, -0.5F, 0.0F);
        this.D_BODYChildChild1_2.addBox(-9.0F, -25.0F, 7.0F, 1, 1, 9, 0.0F);
        this.D_BODYChildChildChild3 = new ModelRenderer(this, 77, 49);
        this.D_BODYChildChildChild3.setRotationPoint(0.0F, 0.0F, 0.0F);
        this.D_BODYChildChildChild3.addBox(-5.25F, -1.5F, -8.5F, 2, 2, 4, 0.0F);
        this.setRotateAngle(D_BODYChildChildChild3, 0.060039326268604934F, 0.0F, 0.0F);
        this.D_BODYChildChildChild4 = new ModelRenderer(this, 77, 49);
        this.D_BODYChildChildChild4.mirror = true;
        this.D_BODYChildChildChild4.setRotationPoint(0.0F, 0.0F, 0.0F);
        this.D_BODYChildChildChild4.addBox(-5.25F, -1.5F, 4.5F, 2, 2, 4, 0.0F);
        this.D_BODYChildChild9 = new ModelRenderer(this, 37, 58);
        this.D_BODYChildChild9.setRotationPoint(9.0F, -0.5F, 0.0F);
        this.D_BODYChildChild9.addBox(6.0F, -13.0F, 7.0F, 1, 5, 1, 0.0F);
        this.Detector.addChild(this.D_BODYChildChild6);
        this.Detector.addChild(this.D_BODYChildChild11);
        this.Detector.addChild(this.D_BODYChildChild0_2);
        this.D_BODYChildChild0_2.addChild(this.Pot1);
        this.Pot1.addChild(this.D_BODYChildChildChild5_1);
        this.Detector.addChild(this.D_BODYChildChild2);
        this.Detector.addChild(this.D_BODYChildChild5_1);
        this.Detector.addChild(this.D_BODYChildChild7_1);
        this.D_BODYChildChild0_1.addChild(this.Flame2);
        this.Detector.addChild(this.D_BODYChildChild3_1);
        this.Detector.addChild(this.D_BODYChildChild1);
        this.Detector.addChild(this.D_BODYChildChild12);
        this.AutomatonMain.addChild(this.Detector);
        this.Detector.addChild(this.D_BODYChildChild4);
        this.Pot1.addChild(this.D_BODYChildChildChild4_1);
        this.Detector.addChild(this.D_BODYChildChild8_1);
        this.Detector.addChild(this.D_BODYChildChild5);
        this.Detector.addChild(this.D_BODYChildChild12_1);
        this.Wing.addChild(this.D_BODYChildChild2_2);
        this.Detector.addChild(this.D_BODYChildChild6_1);
        this.Detector.addChild(this.D_BODYChildChild10_1);
        this.AutomatonMain.addChild(this.Connector);
        this.AutomatonMain.addChild(this.Ammo);
        this.Detector.addChild(this.D_BODYChildChild0);
        this.Detector.addChild(this.Shooter);
        this.Pot1.addChild(this.D_BODYChildChildChild3_1);
        this.Wing.addChild(this.D_BODYChildChild1_3);
        this.Detector.addChild(this.D_BODYChildChild9_1);
        this.Pot2.addChild(this.D_BODYChildChildChild5);
        this.Wing.addChild(this.D_BODYChildChild3_2);
        this.Detector.addChild(this.D_BODYChildChild14_1);
        this.Detector.addChild(this.D_BODYChildChild8);
        this.Detector.addChild(this.D_BODYChildChild14);
        this.Pot1.addChild(this.D_BODYChildChildChild2_1);
        this.Detector.addChild(this.D_BODYChildChild10);
        this.Detector.addChild(this.D_BODYChildChild13_1);
        this.D_BODYChildChild0_2.addChild(this.Flame1);
        this.Detector.addChild(this.D_BODYChildChild7);
        this.Detector.addChild(this.Wing);
        this.Pot2.addChild(this.D_BODYChildChildChild0);
        this.Detector.addChild(this.D_BODYChildChild3);
        this.Detector.addChild(this.D_BODYChildChild1_1);
        this.D_BODYChildChild0_1.addChild(this.Pot2);
        this.Detector.addChild(this.D_BODYChildChild11_1);
        this.Pot2.addChild(this.D_BODYChildChildChild2);
        this.Detector.addChild(this.D_BODYChildChild4_1);
        this.Detector.addChild(this.D_BODYChildChild0_1);
        this.Pot1.addChild(this.D_BODYChildChildChild0_1);
        this.Detector.addChild(this.D_BODYChildChild2_1);
        this.Detector.addChild(this.D_BODYChildChild13);
        this.Detector.addChild(this.D_BODYChildChild1_2);
        this.Pot2.addChild(this.D_BODYChildChildChild3);
        this.Pot2.addChild(this.D_BODYChildChildChild4);
        this.Detector.addChild(this.D_BODYChildChild9);
        animator = ModelAnimator.create();
        this.updateDefaultPose();
    }

    @Override
    public void render(Entity entity, float f, float f1, float f2, float f3, float f4, float f5) {
        animate((IAnimatedEntity) entity, f, f1, f2, f3, f4, f5);
        this.AutomatonMain.render(f5);
    }

    public void animate(IAnimatedEntity entity, float f, float f1, float f2, float f3, float f4, float f5) {
        if(((EntityAutomatonFlying)entity).isAwake()) {
            this.Wing.rotateAngleY += 30;
            this.Pot1.rotateAngleX += 30;
            this.Pot2.rotateAngleX += 30;
        }
    }

    /**
     * This is a helper function from Tabula to set the rotation of model parts
     */
    public void setRotateAngle(ModelRenderer modelRenderer, float x, float y, float z) {
        modelRenderer.rotateAngleX = x;
        modelRenderer.rotateAngleY = y;
        modelRenderer.rotateAngleZ = z;
    }

    @Override
    public void renderStatue() {
        this.resetToDefaultPose();
    }
}
